/**
 * lib/tweets/service.ts
 *
 * Shared Tweets creation/interaction pipeline.
 *
 * Mirrors lib/moments/service.ts's shape — feature flag → level gate →
 * currency resolution/affordability → atomic charge + insert — but simpler:
 * Tweets are Credits-only (no Stars option) and only the optional image is
 * charged; a video embed is always free.
 *
 * @module lib/tweets/service
 */

import { randomUUID } from "crypto";
import { db } from "@/lib/db";
import type { TransactionClient } from "@/lib/db/interface";
import { loadManifest, requireFeatureEnabled } from "@/lib/manifest";
import { getRankForXP } from "@/lib/xp/engine";
import { debitCoins } from "@/lib/economy/coins";
import { isPlanEligible } from "@/lib/plans/eligibility";
import { ApiError, badRequest, forbidden, notFound } from "@/lib/api/errors";
import { insertNotification } from "@/lib/notifications/insert";
import { logger } from "@/lib/logger";

/**
 * Absolute, non-admin-configurable safety ceiling on Tweet content length —
 * mirrored as a DB CHECK constraint in 0039_tweets.sql. The real effective
 * limit (default vs. long-form vs. personal) is computed below and is
 * always <= this.
 */
export const TWEETS_HARD_CHAR_CAP = 7000;

/**
 * Rough average characters-per-word (5.1 avg English word length + 1 space,
 * per Wolfram Language corpus data) used to convert the admin's
 * `tweets_long_max_length` setting — deliberately expressed in WORDS per
 * product decision, since that's the more intuitive unit for an admin
 * setting a "long-form" ceiling — into an enforceable character count.
 */
const WORDS_TO_CHARS_FACTOR = 6;

export type TweetVideoProvider = "youtube" | "tiktok";

// ---------------------------------------------------------------------------
// Video URL parsing
// ---------------------------------------------------------------------------

const YOUTUBE_HOSTS = new Set(["youtube.com", "www.youtube.com", "m.youtube.com", "youtu.be"]);
const TIKTOK_HOSTS = new Set(["tiktok.com", "www.tiktok.com", "vm.tiktok.com", "vt.tiktok.com"]);

/** Extracts an 11-ish char YouTube video ID from any standard URL shape. */
export function parseYouTubeId(rawUrl: string): string | null {
  let u: URL;
  try {
    u = new URL(rawUrl);
  } catch {
    return null;
  }
  const host = u.hostname.toLowerCase();
  if (!YOUTUBE_HOSTS.has(host)) return null;

  if (host === "youtu.be") {
    const id = u.pathname.split("/").filter(Boolean)[0];
    return id && /^[\w-]{6,20}$/.test(id) ? id : null;
  }
  if (u.pathname === "/watch") {
    const id = u.searchParams.get("v");
    return id && /^[\w-]{6,20}$/.test(id) ? id : null;
  }
  const shortsMatch = u.pathname.match(/^\/shorts\/([\w-]{6,20})/);
  if (shortsMatch) return shortsMatch[1];
  const embedMatch = u.pathname.match(/^\/embed\/([\w-]{6,20})/);
  if (embedMatch) return embedMatch[1];
  return null;
}

/** Extracts a numeric TikTok video ID from a full-form `.../video/<id>` URL. */
function extractTikTokIdFromUrl(rawUrl: string): string | null {
  try {
    const u = new URL(rawUrl);
    const host = u.hostname.toLowerCase();
    if (!TIKTOK_HOSTS.has(host)) return null;
    const m = u.pathname.match(/\/video\/(\d+)/);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

/**
 * Resolves a TikTok URL to its numeric video ID.
 *
 * Design note (documented per task spec): TikTok share links come in two
 * shapes — the full form (`tiktok.com/@user/video/<id>`), whose ID we can
 * extract client-side with a regex, and short links (`vm.tiktok.com/<code>`,
 * `vt.tiktok.com/<code>`) generated by TikTok's native "Share > Copy Link"
 * button, which carry no ID in the URL itself — TikTok only reveals it after
 * following the redirect. We resolve those server-side at submit time with a
 * single GET request (redirect: "follow"), read the final resolved URL, and
 * extract the ID from it — this doubles as validating the link is a real,
 * reachable TikTok video before we accept it (an invalid/dead short link
 * fails to resolve to a `/video/<id>` path and is rejected). We didn't use
 * the public oEmbed endpoint (`tiktok.com/oembed`) instead because it 404s
 * on some private/region-locked videos that still resolve fine via a plain
 * redirect follow, and because we only need the ID (not the embed HTML) —
 * rendering uses TikTok's official `embed.js` blockquote embed client-side.
 */
export async function resolveTikTokId(rawUrl: string): Promise<string> {
  const direct = extractTikTokIdFromUrl(rawUrl);
  if (direct) return direct;

  let u: URL;
  try {
    u = new URL(rawUrl);
  } catch {
    throw badRequest("That doesn't look like a valid TikTok link.", "INVALID_TIKTOK_URL");
  }
  if (!TIKTOK_HOSTS.has(u.hostname.toLowerCase())) {
    throw badRequest("Video URL must be a youtube.com/youtu.be or tiktok.com link.", "INVALID_VIDEO_URL");
  }

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 5000);
    const res = await fetch(rawUrl, {
      method: "GET",
      redirect: "follow",
      signal: controller.signal,
      headers: { "User-Agent": "Mozilla/5.0 (compatible; ZobiaBot/1.0)" },
    }).finally(() => clearTimeout(timeout));
    const resolvedId = extractTikTokIdFromUrl(res.url);
    if (resolvedId) return resolvedId;
  } catch (err) {
    logger.error({ err, url: rawUrl }, "[tweets] TikTok short-link resolution failed");
  }

  throw badRequest(
    "Couldn't resolve that TikTok link. Paste the full video URL (tiktok.com/@user/video/...) instead of a shortened share link.",
    "INVALID_TIKTOK_URL"
  );
}

export interface ParsedVideo {
  videoProvider: TweetVideoProvider;
  videoUrl: string;
  videoEmbedId: string;
}

/** Validates and parses a video URL submitted for a Tweet's video embed. */
export async function parseTweetVideo(
  provider: TweetVideoProvider,
  rawUrl: string
): Promise<ParsedVideo> {
  if (provider === "youtube") {
    const id = parseYouTubeId(rawUrl);
    if (!id) throw badRequest("That doesn't look like a valid YouTube video URL.", "INVALID_VIDEO_URL");
    return { videoProvider: "youtube", videoUrl: rawUrl, videoEmbedId: id };
  }
  const id = await resolveTikTokId(rawUrl);
  return { videoProvider: "tiktok", videoUrl: rawUrl, videoEmbedId: id };
}

// ---------------------------------------------------------------------------
// Mentions
// ---------------------------------------------------------------------------

/**
 * Extract `@username` tokens from tweet text (lowercased, de-duplicated).
 * Reuses the exact matching rule already used for Room chat @mentions
 * (lib/notifications/chatPush.ts's parseMentions) so `@username` parsing
 * behaves identically across the app.
 */
export function parseTweetMentions(text: string | null | undefined): string[] {
  if (!text) return [];
  const matches = text.matchAll(/(?:^|[^a-zA-Z0-9_])@([a-zA-Z0-9_]{3,30})/g);
  const set = new Set<string>();
  for (const m of matches) set.add(m[1].toLowerCase());
  return [...set];
}

// ---------------------------------------------------------------------------
// Eligibility / pricing
// ---------------------------------------------------------------------------

export interface TweetsEligibility {
  rankNumber: number;
  xpTotal: number;
  creditBalance: number;
  minLevel: number;
  imageCostCredits: number;
  /** Standard length limit (characters) for non-exempt users. */
  defaultMaxLength: number;
  /** True if this user gets free long-form Tweets (role/plan OR level exempt). */
  isLongFormExempt: boolean;
  /** Admin long-form ceiling, converted from tweets_long_max_length (words) to characters. */
  longMaxLengthChars: number;
  /** This user's personal effective max length (chars), clamped to [defaultMaxLength, longMaxLengthChars]. */
  personalMaxLength: number;
  /** Credits charged for a Tweet over defaultMaxLength when NOT long-form exempt. */
  longTweetCostCredits: number;
}

export async function getTweetsEligibility(userId: string): Promise<TweetsEligibility> {
  const [manifest, userRows] = await Promise.all([
    loadManifest(),
    db.query<{
      xp_total: number;
      coin_balance: number;
      plan: string;
      prestige_count: number | null;
      is_admin: boolean | null;
      is_moderator: boolean | null;
      tweet_max_length: number | null;
    }>(
      `SELECT COALESCE(xp_total, 0) AS xp_total, COALESCE(coin_balance, 0) AS coin_balance,
              plan, prestige_count, is_admin, is_moderator, tweet_max_length
       FROM users WHERE id = $1 AND deleted_at IS NULL LIMIT 1`,
      [userId]
    ),
  ]);
  const row = userRows.rows[0];
  if (!row) throw forbidden("User account not found");
  const rankNumber = getRankForXP(row.xp_total).rankNumber;

  const { defaultMaxLength, longMinLevel, longMinRoles, longMaxLengthWords, imageCostCredits, longTweetCostCredits, minLevel } =
    manifest.tweets;

  const isLongFormExempt =
    rankNumber >= longMinLevel ||
    isPlanEligible(row.plan ?? "free", row.prestige_count ?? 0, longMinRoles, {
      isAdmin: Boolean(row.is_admin),
      isModerator: Boolean(row.is_moderator),
    });

  const longMaxLengthChars = Math.min(longMaxLengthWords * WORDS_TO_CHARS_FACTOR, TWEETS_HARD_CHAR_CAP);
  const personalMaxLength = Math.min(
    Math.max(row.tweet_max_length ?? defaultMaxLength, defaultMaxLength),
    longMaxLengthChars
  );

  return {
    rankNumber,
    xpTotal: row.xp_total,
    creditBalance: row.coin_balance,
    minLevel,
    imageCostCredits,
    defaultMaxLength,
    isLongFormExempt,
    longMaxLengthChars,
    personalMaxLength,
    longTweetCostCredits,
  };
}

/**
 * Clamps a user-requested personal tweet-length preference to
 * [defaultMaxLength, longMaxLengthChars] for storage in
 * `users.tweet_max_length`. Used by PATCH /api/users/me/settings.
 */
export async function clampPersonalTweetMaxLength(userId: string, requested: number): Promise<number> {
  const eligibility = await getTweetsEligibility(userId);
  return Math.min(Math.max(requested, eligibility.defaultMaxLength), eligibility.longMaxLengthChars);
}

export function assertTweetsLevelGate(eligibility: TweetsEligibility): void {
  if (eligibility.rankNumber < eligibility.minLevel) {
    throw forbidden(
      `You must reach Level ${eligibility.minLevel} to post Tweets. Your current level is ${eligibility.rankNumber}.`,
      "TWEETS_LEVEL_TOO_LOW",
      { minLevel: eligibility.minLevel, currentLevel: eligibility.rankNumber }
    );
  }
}

function assertCanAffordImage(eligibility: TweetsEligibility): void {
  if (eligibility.imageCostCredits <= 0) return;
  if (eligibility.creditBalance < eligibility.imageCostCredits) {
    throw new ApiError(
      402,
      "INSUFFICIENT_TWEET_IMAGE_FUNDS",
      "You don't have enough Credits to attach an image to a Tweet.",
      undefined,
      undefined,
      { costCredits: eligibility.imageCostCredits, creditBalance: eligibility.creditBalance }
    );
  }
}

/**
 * Determines whether (and how much) a specific Tweet's content length must
 * be charged for, given the caller's eligibility. Throws TWEET_TOO_LONG if
 * the content exceeds the caller's personal max length (or the hard cap),
 * and a 402 INSUFFICIENT_TWEET_LENGTH_FUNDS if it's chargeable but the
 * caller can't afford it.
 */
function resolveLengthCharge(eligibility: TweetsEligibility, contentLength: number): boolean {
  if (contentLength <= eligibility.defaultMaxLength) return false;

  if (contentLength > eligibility.personalMaxLength) {
    throw new ApiError(
      400,
      "TWEET_TOO_LONG",
      eligibility.isLongFormExempt
        ? `Tweets are limited to ${eligibility.personalMaxLength} characters for your account. Raise your personal limit in Settings (up to ${eligibility.longMaxLengthChars}).`
        : `Tweets over ${eligibility.defaultMaxLength} characters cost ${eligibility.longTweetCostCredits} Credits, up to ${eligibility.personalMaxLength} characters.`,
      undefined,
      undefined,
      { maxLength: eligibility.personalMaxLength }
    );
  }

  if (eligibility.isLongFormExempt) return false; // free long tweet, up to personalMaxLength

  if (eligibility.creditBalance < eligibility.longTweetCostCredits) {
    throw new ApiError(
      402,
      "INSUFFICIENT_TWEET_LENGTH_FUNDS",
      `You don't have enough Credits to post a Tweet over ${eligibility.defaultMaxLength} characters.`,
      undefined,
      undefined,
      { costCredits: eligibility.longTweetCostCredits, creditBalance: eligibility.creditBalance, defaultMaxLength: eligibility.defaultMaxLength }
    );
  }
  return true; // charge longTweetCostCredits
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

export interface CreateTweetInput {
  userId: string;
  content: string | null;
  imageUrl?: string | null;
  video?: ParsedVideo | null;
  /** Set to reply to another Tweet — a reply is just a Tweet with this set. */
  parentTweetId?: string | null;
}

export interface CreateTweetResult {
  id: string;
  createdAt: string;
  imageCostCredits: number;
  imageCharged: boolean;
  longTweetCostCredits: number;
  longTweetCharged: boolean;
}

/**
 * Full Tweets creation pipeline: feature flag → level gate → parent lookup
 * (for replies) → length-charge + image-charge affordability checks →
 * atomic charge(s) + insert + mention rows + parent reply-count bump, all in
 * one DB transaction so a failed insert never leaves a user charged for
 * something that was never posted. Video embeds never cost anything.
 */
export async function createTweet(input: CreateTweetInput): Promise<CreateTweetResult> {
  await requireFeatureEnabled("tweets");

  if (!input.content?.trim() && !input.imageUrl && !input.video) {
    throw badRequest("A Tweet needs text, an image, or a video.", "TWEET_EMPTY");
  }
  const contentLength = input.content?.trim().length ?? 0;
  if (contentLength > TWEETS_HARD_CHAR_CAP) {
    throw badRequest(`Tweets cannot exceed ${TWEETS_HARD_CHAR_CAP} characters.`, "TWEET_TOO_LONG");
  }

  const eligibility = await getTweetsEligibility(input.userId);
  assertTweetsLevelGate(eligibility);

  if (input.parentTweetId) {
    const parent = await getTweet(input.parentTweetId);
    if (!parent) throw notFound("The Tweet you're replying to was not found");
  }

  const willChargeImage = Boolean(input.imageUrl) && eligibility.imageCostCredits > 0;
  if (input.imageUrl) assertCanAffordImage(eligibility);
  const willChargeLength = resolveLengthCharge(eligibility, contentLength);

  const mentionedUsernames = parseTweetMentions(input.content);
  const referenceId = `tweet_create:${input.userId}:${randomUUID()}`;

  const created = await db.transaction(async (tx: TransactionClient) => {
    if (willChargeImage) {
      await debitCoins(
        input.userId,
        eligibility.imageCostCredits,
        "tweet_image_created",
        referenceId,
        "Attached an image to a Tweet",
        {},
        tx
      );
    }
    if (willChargeLength) {
      await debitCoins(
        input.userId,
        eligibility.longTweetCostCredits,
        "tweet_long_created",
        referenceId,
        "Posted a long Tweet",
        { defaultMaxLength: eligibility.defaultMaxLength },
        tx
      );
    }

    const { rows } = await tx.query<{ id: string; created_at: string }>(
      `INSERT INTO tweets (user_id, parent_tweet_id, content, image_url, video_provider, video_url, video_embed_id)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       RETURNING id, created_at`,
      [
        input.userId,
        input.parentTweetId ?? null,
        input.content?.trim() || null,
        input.imageUrl ?? null,
        input.video?.videoProvider ?? null,
        input.video?.videoUrl ?? null,
        input.video?.videoEmbedId ?? null,
      ]
    );
    const tweet = rows[0];

    if (input.parentTweetId) {
      await tx.query(`UPDATE tweets SET replies_count = replies_count + 1 WHERE id = $1`, [input.parentTweetId]);
    }

    let mentionedUserIds: { id: string; username: string }[] = [];
    if (mentionedUsernames.length > 0) {
      const { rows: mentionRows } = await tx.query<{ id: string; username: string }>(
        `SELECT id, username FROM users WHERE LOWER(username) = ANY($1) AND deleted_at IS NULL`,
        [mentionedUsernames]
      );
      mentionedUserIds = mentionRows.filter((r) => r.id !== input.userId);
      for (const m of mentionedUserIds) {
        await tx.query(
          `INSERT INTO tweet_mentions (tweet_id, mentioned_user_id) VALUES ($1, $2)
           ON CONFLICT (tweet_id, mentioned_user_id) DO NOTHING`,
          [tweet.id, m.id]
        );
      }
    }

    return { tweet, mentionedUserIds };
  });

  // Fire mention notifications through the existing notifications pipeline,
  // best-effort — a notification failure must never undo a posted Tweet.
  if (created.mentionedUserIds.length > 0) {
    const { rows: authorRows } = await db.query<{ username: string }>(
      `SELECT username FROM users WHERE id = $1 LIMIT 1`,
      [input.userId]
    );
    const authorUsername = authorRows[0]?.username ?? "Someone";
    await Promise.all(
      created.mentionedUserIds.map((m) =>
        insertNotification(
          db,
          m.id,
          "tweet_mention",
          "You were mentioned in a Tweet",
          `@${authorUsername} mentioned you in a Tweet.`,
          { tweetId: created.tweet.id, authorUsername }
        )
      )
    ).catch((err) => logger.error({ err }, "[tweets] mention notification insert failed"));
  }

  return {
    id: created.tweet.id,
    createdAt: created.tweet.created_at,
    imageCostCredits: eligibility.imageCostCredits,
    imageCharged: willChargeImage,
    longTweetCostCredits: eligibility.longTweetCostCredits,
    longTweetCharged: willChargeLength,
  };
}

// ---------------------------------------------------------------------------
// Likes
// ---------------------------------------------------------------------------

async function getTweet(tweetId: string): Promise<{ id: string; user_id: string } | null> {
  const { rows } = await db.query<{ id: string; user_id: string }>(
    `SELECT id, user_id FROM tweets WHERE id = $1 AND deleted_at IS NULL LIMIT 1`,
    [tweetId]
  );
  return rows[0] ?? null;
}

/** Toggle-style like: liking an already-liked Tweet or unliking an unliked one is a no-op. */
export async function likeTweet(tweetId: string, userId: string): Promise<{ likesCount: number; liked: boolean }> {
  await requireFeatureEnabled("tweets");
  const tweet = await getTweet(tweetId);
  if (!tweet) throw notFound("Tweet not found");

  await db.transaction(async (tx) => {
    await tx.query(
      `INSERT INTO tweet_likes (tweet_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING`,
      [tweetId, userId]
    );
    await tx.query(
      `UPDATE tweets SET likes_count = (SELECT COUNT(*) FROM tweet_likes WHERE tweet_id = $1) WHERE id = $1`,
      [tweetId]
    );
  });

  const { rows } = await db.query<{ likes_count: number }>(`SELECT likes_count FROM tweets WHERE id = $1`, [tweetId]);
  return { likesCount: rows[0]?.likes_count ?? 0, liked: true };
}

export async function unlikeTweet(tweetId: string, userId: string): Promise<{ likesCount: number; liked: boolean }> {
  await requireFeatureEnabled("tweets");
  const tweet = await getTweet(tweetId);
  if (!tweet) throw notFound("Tweet not found");

  await db.transaction(async (tx) => {
    await tx.query(`DELETE FROM tweet_likes WHERE tweet_id = $1 AND user_id = $2`, [tweetId, userId]);
    await tx.query(
      `UPDATE tweets SET likes_count = (SELECT COUNT(*) FROM tweet_likes WHERE tweet_id = $1) WHERE id = $1`,
      [tweetId]
    );
  });

  const { rows } = await db.query<{ likes_count: number }>(`SELECT likes_count FROM tweets WHERE id = $1`, [tweetId]);
  return { likesCount: rows[0]?.likes_count ?? 0, liked: false };
}

// ---------------------------------------------------------------------------
// Pin / delete
// ---------------------------------------------------------------------------

/** Pins a tweet to the caller's profile, atomically unpinning any previous pin. */
export async function pinTweet(tweetId: string, userId: string): Promise<void> {
  const tweet = await getTweet(tweetId);
  if (!tweet) throw notFound("Tweet not found");
  if (tweet.user_id !== userId) throw forbidden("Cannot pin another user's Tweet");

  await db.transaction(async (tx) => {
    await tx.query(`UPDATE tweets SET is_pinned = false WHERE user_id = $1 AND is_pinned = true`, [userId]);
    await tx.query(`UPDATE tweets SET is_pinned = true WHERE id = $1`, [tweetId]);
  });
}

export async function unpinTweet(tweetId: string, userId: string): Promise<void> {
  const tweet = await getTweet(tweetId);
  if (!tweet) throw notFound("Tweet not found");
  if (tweet.user_id !== userId) throw forbidden("Cannot unpin another user's Tweet");
  await db.query(`UPDATE tweets SET is_pinned = false WHERE id = $1`, [tweetId]);
}

export async function deleteTweet(tweetId: string, userId: string): Promise<void> {
  const tweet = await getTweet(tweetId);
  if (!tweet) throw notFound("Tweet not found");
  if (tweet.user_id !== userId) throw forbidden("Cannot delete another user's Tweet");
  await db.query(`UPDATE tweets SET deleted_at = NOW(), is_pinned = false WHERE id = $1`, [tweetId]);
}

// ---------------------------------------------------------------------------
// Retweets (plain + quote)
// ---------------------------------------------------------------------------

export interface RetweetResult {
  retweetsCount: number;
  retweeted: boolean;
}

/**
 * Retweets (or quote-retweets, when `quoteContent` is set) a Tweet. Same
 * feature/level gate as posting a Tweet — no separate charge, per product
 * decision. Toggle semantics: retweeting an already-retweeted Tweet just
 * updates the quote text (or clears it) rather than erroring, so "change my
 * quote" is retweet-again, not un-retweet-then-retweet.
 */
export async function retweetTweet(tweetId: string, userId: string, quoteContent?: string | null): Promise<RetweetResult> {
  await requireFeatureEnabled("tweets");
  const eligibility = await getTweetsEligibility(userId);
  assertTweetsLevelGate(eligibility);

  const tweet = await getTweet(tweetId);
  if (!tweet) throw notFound("Tweet not found");
  if (tweet.user_id === userId) throw badRequest("You cannot retweet your own Tweet", "CANNOT_RETWEET_OWN");

  const trimmedQuote = quoteContent?.trim() || null;
  if (trimmedQuote && trimmedQuote.length > TWEETS_HARD_CHAR_CAP) {
    throw badRequest(`Quote text cannot exceed ${TWEETS_HARD_CHAR_CAP} characters.`, "TWEET_TOO_LONG");
  }

  await db.transaction(async (tx) => {
    const { rows: existing } = await tx.query<{ id: string }>(
      `SELECT id FROM tweet_retweets WHERE tweet_id = $1 AND user_id = $2`,
      [tweetId, userId]
    );
    if (existing[0]) {
      await tx.query(`UPDATE tweet_retweets SET quote_content = $3 WHERE tweet_id = $1 AND user_id = $2`, [
        tweetId,
        userId,
        trimmedQuote,
      ]);
    } else {
      await tx.query(`INSERT INTO tweet_retweets (tweet_id, user_id, quote_content) VALUES ($1, $2, $3)`, [
        tweetId,
        userId,
        trimmedQuote,
      ]);
      await tx.query(`UPDATE tweets SET retweets_count = retweets_count + 1 WHERE id = $1`, [tweetId]);
    }
  });

  if (mentionedInQuote(trimmedQuote).length > 0) {
    // Quote-retweet mentions notify the same way top-level Tweet mentions do,
    // but quotes don't get their own tweet_mentions rows (there's no separate
    // "quote tweet" row — the mention lives on the retweet, not a tweet).
    const usernames = mentionedInQuote(trimmedQuote);
    const { rows: mentionRows } = await db.query<{ id: string; username: string }>(
      `SELECT id, username FROM users WHERE LOWER(username) = ANY($1) AND deleted_at IS NULL AND id != $2`,
      [usernames, userId]
    );
    const { rows: authorRows } = await db.query<{ username: string }>(`SELECT username FROM users WHERE id = $1`, [userId]);
    const authorUsername = authorRows[0]?.username ?? "Someone";
    await Promise.all(
      mentionRows.map((m) =>
        insertNotification(
          db,
          m.id,
          "tweet_mention",
          "You were mentioned in a Retweet",
          `@${authorUsername} mentioned you in a Retweet.`,
          { tweetId, authorUsername }
        )
      )
    ).catch((err) => logger.error({ err }, "[tweets] retweet mention notification insert failed"));
  }

  const { rows } = await db.query<{ retweets_count: number }>(`SELECT retweets_count FROM tweets WHERE id = $1`, [tweetId]);
  return { retweetsCount: rows[0]?.retweets_count ?? 0, retweeted: true };
}

function mentionedInQuote(quote: string | null): string[] {
  return parseTweetMentions(quote);
}

export async function unretweetTweet(tweetId: string, userId: string): Promise<RetweetResult> {
  await requireFeatureEnabled("tweets");
  const tweet = await getTweet(tweetId);
  if (!tweet) throw notFound("Tweet not found");

  await db.transaction(async (tx) => {
    const { rowCount } = await tx.query(`DELETE FROM tweet_retweets WHERE tweet_id = $1 AND user_id = $2`, [tweetId, userId]);
    if (rowCount) {
      await tx.query(`UPDATE tweets SET retweets_count = GREATEST(retweets_count - 1, 0) WHERE id = $1`, [tweetId]);
    }
  });

  const { rows } = await db.query<{ retweets_count: number }>(`SELECT retweets_count FROM tweets WHERE id = $1`, [tweetId]);
  return { retweetsCount: rows[0]?.retweets_count ?? 0, retweeted: false };
}
