/**
 * apps/android/src/main.tsx
 *
 * App bootstrap:
 * 1. i18n init
 * 2. Auth store
 * 3. QueryClientProvider (per-query IndexedDB persister — see lib/query/client.ts,
 *    no PersistQueryClientProvider wrapper needed for that pattern)
 * 4. TanStack Router
 * 5. Capacitor SplashScreen.hide() after mount
 */

import './styles/globals.css';
import './lib/i18n'; // Side-effect: initialise i18n

import React from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClientProvider } from '@tanstack/react-query';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import { SplashScreen } from '@capacitor/splash-screen';

import { queryClient } from '@/lib/query/client';
import { AuthProvider } from '@/lib/auth/store';
import { FloatingRewardProvider } from '@/components/notifications/FloatingRewardProvider';
import { installGlobalErrorHandlers } from '@/lib/debug/logStore';
import { DebugOverlay } from '@/components/debug/DebugOverlay';
import { initGooglePlayBilling } from '@/lib/payments/googlePlay';
import { initAdEventQueueFlush } from '@/lib/ads/adEventQueue';
import { applyStoredLanguagePref } from '@/lib/i18n';

// Install before anything else so startup errors are captured.
installGlobalErrorHandlers();

// ZSB-14 fix: this was fully implemented but never called anywhere, so it
// could never actually run. It overlays the durable Capacitor-Preferences-
// backed language choice on top of i18next-browser-languagedetector's
// localStorage-based restore (`./lib/i18n`'s side-effect init above, which
// has already run synchronously by this point since `initImmediate: false`),
// so a chosen language survives even a WebView "Clear cache" that wipes
// localStorage but leaves native SharedPreferences intact.
void applyStoredLanguagePref();

// ZB-AND-11 fix: wires the periodic + backgrounding flush triggers for the
// batched ad event queue (see lib/ads/adEventQueue.ts).
initAdEventQueueFlush();

// Import route tree — generated by TanStackRouterVite plugin
import { routeTree } from './routeTree.gen';

const router = createRouter({ routeTree });

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

function App() {
  React.useEffect(() => {
    // Hide splash screen once React has mounted
    SplashScreen.hide().catch(() => {});
    // Connect to Google Play Billing early so product prices/offers are ready
    // by the time the user reaches a purchase screen. Never blocks rendering
    // (e.g. Play Store unavailable on some emulators/test devices) — errors
    // are logged, not thrown.
    initGooglePlayBilling().catch((err) => console.error('[googlePlay] init failed:', err));
  }, []);

  return (
    <QueryClientProvider client={queryClient}>
      <AuthProvider>
        <FloatingRewardProvider>
          <RouterProvider router={router} />
        </FloatingRewardProvider>
      </AuthProvider>
    </QueryClientProvider>
  );
}

const rootEl = document.getElementById('root');
if (rootEl) {
  ReactDOM.createRoot(rootEl).render(
    <React.StrictMode>
      <App />
      <DebugOverlay />
    </React.StrictMode>
  );
}
