/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as MomentsIndexRouteImport } from './routes/moments/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as AnswersIndexRouteImport } from './routes/answers/index'
import { Route as AdsIndexRouteImport } from './routes/ads/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as MomentsCreateRouteImport } from './routes/moments/create'
import { Route as MessagesConversationIdRouteImport } from './routes/messages/$conversationId'
import { Route as GamesSavedRouteImport } from './routes/games/saved'
import { Route as GamesSlugRouteImport } from './routes/games/$slug'
import { Route as BlogsNewRouteImport } from './routes/blogs/new'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AnswersAskRouteImport } from './routes/answers/ask'
import { Route as AnswersQuestionIdRouteImport } from './routes/answers/$questionId'
import { Route as BusinessPagesIndexRouteImport } from './routes/business/pages/index'
import { Route as BusinessAdsIndexRouteImport } from './routes/business/ads/index'
import { Route as BlogsSlugIndexRouteImport } from './routes/blogs/$slug/index'
import { Route as BusinessPagesPageIdRouteImport } from './routes/business/pages/$pageId'
import { Route as BlogsSlugPostSlugRouteImport } from './routes/blogs/$slug/$postSlug'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsIndexRoute = MomentsIndexRouteImport.update({
  id: '/moments/',
  path: '/moments/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswersIndexRoute = AnswersIndexRouteImport.update({
  id: '/answers/',
  path: '/answers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsCreateRoute = MomentsCreateRouteImport.update({
  id: '/moments/create',
  path: '/moments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSavedRoute = GamesSavedRouteImport.update({
  id: '/games/saved',
  path: '/games/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsNewRoute = BlogsNewRouteImport.update({
  id: '/blogs/new',
  path: '/blogs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/auth/two-factor',
  path: '/auth/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswersAskRoute = AnswersAskRouteImport.update({
  id: '/answers/ask',
  path: '/answers/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswersQuestionIdRoute = AnswersQuestionIdRouteImport.update({
  id: '/answers/$questionId',
  path: '/answers/$questionId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPagesIndexRoute = BusinessPagesIndexRouteImport.update({
  id: '/business/pages/',
  path: '/business/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAdsIndexRoute = BusinessAdsIndexRouteImport.update({
  id: '/business/ads/',
  path: '/business/ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugIndexRoute = BlogsSlugIndexRouteImport.update({
  id: '/blogs/$slug/',
  path: '/blogs/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPagesPageIdRoute = BusinessPagesPageIdRouteImport.update({
  id: '/business/pages/$pageId',
  path: '/business/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugPostSlugRoute = BlogsSlugPostSlugRouteImport.update({
  id: '/blogs/$slug/$postSlug',
  path: '/blogs/$slug/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/wallet': typeof WalletRoute
  '/answers/$questionId': typeof AnswersQuestionIdRoute
  '/answers/ask': typeof AnswersAskRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/blogs/new': typeof BlogsNewRoute
  '/games/$slug': typeof GamesSlugRoute
  '/games/saved': typeof GamesSavedRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/moments/create': typeof MomentsCreateRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/ads/': typeof AdsIndexRoute
  '/answers/': typeof AnswersIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/games/': typeof GamesIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/moments/': typeof MomentsIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/blogs/$slug/$postSlug': typeof BlogsSlugPostSlugRoute
  '/business/pages/$pageId': typeof BusinessPagesPageIdRoute
  '/blogs/$slug/': typeof BlogsSlugIndexRoute
  '/business/ads/': typeof BusinessAdsIndexRoute
  '/business/pages/': typeof BusinessPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/wallet': typeof WalletRoute
  '/answers/$questionId': typeof AnswersQuestionIdRoute
  '/answers/ask': typeof AnswersAskRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/blogs/new': typeof BlogsNewRoute
  '/games/$slug': typeof GamesSlugRoute
  '/games/saved': typeof GamesSavedRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/moments/create': typeof MomentsCreateRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/ads': typeof AdsIndexRoute
  '/answers': typeof AnswersIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/business': typeof BusinessIndexRoute
  '/games': typeof GamesIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/moments': typeof MomentsIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/blogs/$slug/$postSlug': typeof BlogsSlugPostSlugRoute
  '/business/pages/$pageId': typeof BusinessPagesPageIdRoute
  '/blogs/$slug': typeof BlogsSlugIndexRoute
  '/business/ads': typeof BusinessAdsIndexRoute
  '/business/pages': typeof BusinessPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/wallet': typeof WalletRoute
  '/answers/$questionId': typeof AnswersQuestionIdRoute
  '/answers/ask': typeof AnswersAskRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/blogs/new': typeof BlogsNewRoute
  '/games/$slug': typeof GamesSlugRoute
  '/games/saved': typeof GamesSavedRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/moments/create': typeof MomentsCreateRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/ads/': typeof AdsIndexRoute
  '/answers/': typeof AnswersIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/games/': typeof GamesIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/moments/': typeof MomentsIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/blogs/$slug/$postSlug': typeof BlogsSlugPostSlugRoute
  '/business/pages/$pageId': typeof BusinessPagesPageIdRoute
  '/blogs/$slug/': typeof BlogsSlugIndexRoute
  '/business/ads/': typeof BusinessAdsIndexRoute
  '/business/pages/': typeof BusinessPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/notifications'
    | '/settings'
    | '/stats'
    | '/wallet'
    | '/answers/$questionId'
    | '/answers/ask'
    | '/auth/login'
    | '/auth/register'
    | '/auth/two-factor'
    | '/blogs/new'
    | '/games/$slug'
    | '/games/saved'
    | '/messages/$conversationId'
    | '/moments/create'
    | '/profile/$username'
    | '/rooms/$roomId'
    | '/ads/'
    | '/answers/'
    | '/blogs/'
    | '/business/'
    | '/games/'
    | '/messages/'
    | '/moments/'
    | '/rooms/'
    | '/blogs/$slug/$postSlug'
    | '/business/pages/$pageId'
    | '/blogs/$slug/'
    | '/business/ads/'
    | '/business/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/notifications'
    | '/settings'
    | '/stats'
    | '/wallet'
    | '/answers/$questionId'
    | '/answers/ask'
    | '/auth/login'
    | '/auth/register'
    | '/auth/two-factor'
    | '/blogs/new'
    | '/games/$slug'
    | '/games/saved'
    | '/messages/$conversationId'
    | '/moments/create'
    | '/profile/$username'
    | '/rooms/$roomId'
    | '/ads'
    | '/answers'
    | '/blogs'
    | '/business'
    | '/games'
    | '/messages'
    | '/moments'
    | '/rooms'
    | '/blogs/$slug/$postSlug'
    | '/business/pages/$pageId'
    | '/blogs/$slug'
    | '/business/ads'
    | '/business/pages'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/notifications'
    | '/settings'
    | '/stats'
    | '/wallet'
    | '/answers/$questionId'
    | '/answers/ask'
    | '/auth/login'
    | '/auth/register'
    | '/auth/two-factor'
    | '/blogs/new'
    | '/games/$slug'
    | '/games/saved'
    | '/messages/$conversationId'
    | '/moments/create'
    | '/profile/$username'
    | '/rooms/$roomId'
    | '/ads/'
    | '/answers/'
    | '/blogs/'
    | '/business/'
    | '/games/'
    | '/messages/'
    | '/moments/'
    | '/rooms/'
    | '/blogs/$slug/$postSlug'
    | '/business/pages/$pageId'
    | '/blogs/$slug/'
    | '/business/ads/'
    | '/business/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  WalletRoute: typeof WalletRoute
  AnswersQuestionIdRoute: typeof AnswersQuestionIdRoute
  AnswersAskRoute: typeof AnswersAskRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  BlogsNewRoute: typeof BlogsNewRoute
  GamesSlugRoute: typeof GamesSlugRoute
  GamesSavedRoute: typeof GamesSavedRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  MomentsCreateRoute: typeof MomentsCreateRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  AdsIndexRoute: typeof AdsIndexRoute
  AnswersIndexRoute: typeof AnswersIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  MomentsIndexRoute: typeof MomentsIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  BlogsSlugPostSlugRoute: typeof BlogsSlugPostSlugRoute
  BusinessPagesPageIdRoute: typeof BusinessPagesPageIdRoute
  BlogsSlugIndexRoute: typeof BlogsSlugIndexRoute
  BusinessAdsIndexRoute: typeof BusinessAdsIndexRoute
  BusinessPagesIndexRoute: typeof BusinessPagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments/': {
      id: '/moments/'
      path: '/moments'
      fullPath: '/moments/'
      preLoaderRoute: typeof MomentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answers/': {
      id: '/answers/'
      path: '/answers'
      fullPath: '/answers/'
      preLoaderRoute: typeof AnswersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/': {
      id: '/ads/'
      path: '/ads'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments/create': {
      id: '/moments/create'
      path: '/moments/create'
      fullPath: '/moments/create'
      preLoaderRoute: typeof MomentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/saved': {
      id: '/games/saved'
      path: '/games/saved'
      fullPath: '/games/saved'
      preLoaderRoute: typeof GamesSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/new': {
      id: '/blogs/new'
      path: '/blogs/new'
      fullPath: '/blogs/new'
      preLoaderRoute: typeof BlogsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/auth/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answers/ask': {
      id: '/answers/ask'
      path: '/answers/ask'
      fullPath: '/answers/ask'
      preLoaderRoute: typeof AnswersAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answers/$questionId': {
      id: '/answers/$questionId'
      path: '/answers/$questionId'
      fullPath: '/answers/$questionId'
      preLoaderRoute: typeof AnswersQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/pages/': {
      id: '/business/pages/'
      path: '/business/pages'
      fullPath: '/business/pages/'
      preLoaderRoute: typeof BusinessPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/ads/': {
      id: '/business/ads/'
      path: '/business/ads'
      fullPath: '/business/ads/'
      preLoaderRoute: typeof BusinessAdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug/': {
      id: '/blogs/$slug/'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug/'
      preLoaderRoute: typeof BlogsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/pages/$pageId': {
      id: '/business/pages/$pageId'
      path: '/business/pages/$pageId'
      fullPath: '/business/pages/$pageId'
      preLoaderRoute: typeof BusinessPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug/$postSlug': {
      id: '/blogs/$slug/$postSlug'
      path: '/blogs/$slug/$postSlug'
      fullPath: '/blogs/$slug/$postSlug'
      preLoaderRoute: typeof BlogsSlugPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  WalletRoute: WalletRoute,
  AnswersQuestionIdRoute: AnswersQuestionIdRoute,
  AnswersAskRoute: AnswersAskRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  BlogsNewRoute: BlogsNewRoute,
  GamesSlugRoute: GamesSlugRoute,
  GamesSavedRoute: GamesSavedRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  MomentsCreateRoute: MomentsCreateRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  AdsIndexRoute: AdsIndexRoute,
  AnswersIndexRoute: AnswersIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  MomentsIndexRoute: MomentsIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  BlogsSlugPostSlugRoute: BlogsSlugPostSlugRoute,
  BusinessPagesPageIdRoute: BusinessPagesPageIdRoute,
  BlogsSlugIndexRoute: BlogsSlugIndexRoute,
  BusinessAdsIndexRoute: BusinessAdsIndexRoute,
  BusinessPagesIndexRoute: BusinessPagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
